<div class="home-post">

    <article class="article1">
        <header>
            <h2>What is <span>ziown?</span></h2>
        </header>
        <p>Ziown strives to be the easiest way to collect information over the Internet.</p>

        <p>Our HTML form builder helps you create contact forms, online surveys, and invitations so you can collect the
            data, registrations and online payments you need without writing a single line of code. </p>

    </article>
    <article class="article2 clear">
        <p>Ziown strives to be the easiest way to collect information over the Internet.</p>

        <p>Our HTML form builder helps you create contact forms, online surveys, and invitations so you can collect the
            data, registrations and online payments you need without writing a single line of code. </p>
    </article>
</div>

<div class="featured-list">

    <div class="featured-block roundS">
        <h3>Form <span>Builder</span></h3>
        <ul class="fListing">
            <li>5 Users</li>
            <li>Unlimited Forms</li>
            <li>Unlimited Reports</li>
            <li>Maximum Fields*</li>
            <li>3,000 Entries / Month</li>
            <li>1GB Storage</li>
            <li>SSL Encryption</li>
            <li>Payment Integration</li>
        </ul>
        <span class="details"><a href="#">View Details</a></span>
    </div>
    <div class="featured-block1 roundS">
        <h3>Form <span>Builder</span></h3>
        <ul class="fListing">
            <li>5 Users</li>
            <li>Unlimited Forms</li>
            <li>Unlimited Reports</li>
            <li>Maximum Fields*</li>
            <li>3,000 Entries / Month</li>
            <li>1GB Storage</li>
            <li>SSL Encryption</li>
            <li>Payment Integration</li>
        </ul>
        <span class="details"><a href="#">View Details</a></span>
    </div>
    <div class="featured-block2 roundS">
        <h3>Form <span>Builder</span></h3>
        <ul class="fListing">
            <li>5 Users</li>
            <li>Unlimited Forms</li>
            <li>Unlimited Reports</li>
            <li>Maximum Fields*</li>
            <li>3,000 Entries / Month</li>
            <li>1GB Storage</li>
            <li>SSL Encryption</li>
            <li>Payment Integration</li>
        </ul>
        <span class="details"><a href="#">View Details</a></span>
    </div>

    <div class="featured-block3 roundS">
        <h3>Form <span>Builder</span></h3>
        <ul class="fListing">
            <li>5 Users</li>
            <li>Unlimited Forms</li>
            <li>Unlimited Reports</li>
            <li>Maximum Fields*</li>
            <li>3,000 Entries / Month</li>
            <li>1GB Storage</li>
            <li>SSL Encryption</li>
            <li>Payment Integration</li>
        </ul>
        <span class="details"><a href="#">View Details</a></span>
    </div>


</div>