<div class="block">

    <div class="block_head">
        <h2>Pages</h2>

        <ul>
            <li><a href="#">Edit pages</a></li>
            <li><a href="#">Add page</a></li>
        </ul>
    </div>		<!-- .block_head ends -->

    <div class="block_content">

        <form action="" method="post">

            <table cellpadding="0" cellspacing="0" width="100%">

                <tr>
                    <td width="10"><input type="checkbox" class="check_all" /></td>
                    <th>Page title</th>
                    <th>Status</th>
                    <th>Date created</th>
                    <th>Author</th>
                    <td>&nbsp;</td>
                </tr>

                <tr>
                    <td><input type="checkbox" /></td>
                    <td><a href="#">Lorem ipsum dolor</a></td>
                    <td>Published</td>
                    <td>20.03.2010</td>
                    <td><a href="#">John Doe</a></td>
                    <td class="delete"><a href="#">Delete</a></td>
                </tr>

                <tr>
                    <td><input type="checkbox" /></td>
                    <td><a href="#">In ac libero nunc, vel congue neque</a></td>
                    <td>Published</td>
                    <td>18.03.2010</td>
                    <td><a href="#">John Doe</a></td>
                    <td class="delete"><a href="#">Delete</a></td>
                </tr>

                <tr>
                    <td><input type="checkbox" /></td>
                    <td><a href="#">Lorem ipsum dolor</a></td>
                    <td>Published</td>
                    <td>20.03.2010</td>
                    <td><a href="#">John Doe</a></td>
                    <td class="delete"><a href="#">Delete</a></td>
                </tr>

                <tr>
                    <td><input type="checkbox" /></td>
                    <td><a href="#">In ac libero nunc, vel congue neque</a></td>
                    <td>Published</td>
                    <td>18.03.2010</td>
                    <td><a href="#">John Doe</a></td>
                    <td class="delete"><a href="#">Delete</a></td>
                </tr>

                <tr>
                    <td><input type="checkbox" /></td>
                    <td><a href="#">Lorem ipsum dolor</a></td>
                    <td>Published</td>
                    <td>20.03.2010</td>
                    <td><a href="#">John Doe</a></td>
                    <td class="delete"><a href="#">Delete</a></td>
                </tr>

                <tr>
                    <td><input type="checkbox" /></td>
                    <td><a href="#">In ac libero nunc, vel congue neque</a></td>
                    <td>Published</td>
                    <td>18.03.2010</td>
                    <td><a href="#">John Doe</a></td>
                    <td class="delete"><a href="#">Delete</a></td>
                </tr>

                <tr>
                    <td><input type="checkbox" /></td>
                    <td><a href="#">Lorem ipsum dolor</a></td>
                    <td>Published</td>
                    <td>20.03.2010</td>
                    <td><a href="#">John Doe</a></td>
                    <td class="delete"><a href="#">Delete</a></td>
                </tr>

                <tr>
                    <td><input type="checkbox" /></td>
                    <td><a href="#">In ac libero nunc, vel congue neque</a></td>
                    <td>Published</td>
                    <td>18.03.2010</td>
                    <td><a href="#">John Doe</a></td>
                    <td class="delete"><a href="#">Delete</a></td>
                </tr>

            </table>

            <div class="tableactions">
                <select>
                    <option>Actions</option>
                    <option>Delete</option>
                    <option>Edit</option>
                </select>

                <input type="submit" class="submit tiny" value="Apply to selected" />
            </div>		<!-- .tableactions ends -->



            <div class="paggination right">
                <a href="#">&laquo;</a>
                <a href="#" class="active">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
                <a href="#">5</a>
                <a href="#">6</a>
                <a href="#">&raquo;</a>
            </div>		<!-- .paggination ends -->

        </form>

    </div>		<!-- .block_content ends -->

</div>		<!-- .block ends -->


<div class="block">

    <div class="block_head">
        <h2>Forms</h2>

        <form action="" method="post">
            <input type="text" class="text" value="Search" />
        </form>
    </div>		<!-- .block_head ends -->



    <div class="block_content">

        <div class="message errormsg"><p>An error message goes here</p></div>

        <div class="message success"><p>A success message goes here</p></div>

        <div class="message info"><p>An informative message goes here</p></div>

        <div class="message warning"><p>A warning message goes here</p></div>


        <form action="" method="post">
            <p>
                <label>Small input label:</label><br />
                <input type="text" class="text small" />
                <span class="note">*A note</span>
            </p>

            <p>
                <label>Medium input label:</label><br />
                <input type="text" class="text medium error" />
                <span class="note error">Error!</span>
            </p>

            <p>
                <label>Big input label:</label><br />
                <input type="text" class="text big" />
            </p>

            <p>
                <label>Textarea label:</label><br />
                <textarea class="wysiwyg"></textarea>
            </p>

            <p>
                <label>Pick a date:</label>
                <input type="text" class="text date_picker" />
            </p>


            <p><label>Select label:</label> <br />

                <select class="styled">
                    <optgroup label="Group 1">
                        <option>Option one</option>
                        <option>Option two</option>
                        <option>Option three</option>
                    </optgroup>

                    <optgroup label="Group 2">
                        <option>Option one</option>
                        <option>Option two</option>
                        <option>Option three</option>
                    </optgroup>

                    <optgroup label="Group 3">
                        <option>Option one</option>
                        <option>Option two</option>
                        <option>Option three</option>
                    </optgroup>
                </select></p>


            <p class="fileupload">
                <label>File input label:</label><br />
                <input type="file" />
            </p>

            <p>
                <input type="checkbox" class="checkbox" checked="checked" id="cbdemo1" /> <label for="cbdemo1">Checkbox label</label>
                <input type="checkbox" class="checkbox" id="cbdemo2" /> <label for="cbdemo2">Checkbox label</label>
            </p>

            <p><input type="radio" checked="checked" class="radio" /> <label>Radio button label</label></p>

            <hr />

            <p>
                <input type="submit" class="submit small" value="Submit" />
                <input type="submit" class="submit mid" value="Long submit" />
                <input type="submit" class="submit long" value="Even longer submit" />
            </p>
        </form>


    </div>		<!-- .block_content ends -->
</div>		<!-- .block ends -->

<div class="block small left">

    <div class="block_head">
        <h2>Left column</h2>
    </div>		<!-- .block_head ends -->



    <div class="block_content">

        <form action="" method="post">
            <p>
                <label>Small input label:</label><br />
                <input type="text" class="text" />
            </p>

            <p>
                <label>Text area label:</label><br />
                <textarea rows="5" cols="50"></textarea>
            </p>

            <p>Praesent justo risus, suscipit eget volutpat ac, fermentum ac.</p>

            <p><input type="submit" class="submit small" value="Submit" /></p>
        </form>

    </div>		<!-- .block_content ends -->

</div>		<!-- .leftcol ends -->

<div class="block small right">

    <div class="block_head">
        <h2>Right column</h2>
    </div>		<!-- .block_head ends -->



    <div class="block_content">

        <h2>Headline</h2>
        <p>Quisque felis nunc, <a href="demo" rel="facebox">open modal</a> lacinia at, viverra sit amet ligula. Praesent justo risus, suscipit eget volutpat ac, fermentum ac massa. Sed at justo velit. Maecenas dapibus sem nec quam cursus.</p>


        <h3>Headline</h3>
        <ul>
            <li>Proin volutpat</li>
            <li>Praesent justo risus, suscipit eget</li>
            <li>Morbi facilisis felis ac sapien</li>
        </ul>


        <h4>Headline</h4>
        <ol>
            <li>Proin volutpat</li>
            <li>Praesent justo risus, suscipit eget</li>
            <li>Morbi facilisis felis ac sapien</li>
        </ol>

    </div>		<!-- .block_content ends -->

</div>		<!-- .rightcol ends -->

<div class="block">

    <div class="block_head">
        <h2>Big text box with tabs</h2>

        <ul class="tabs">
            <li><a href="#tab1">Tab 1</a></li>
            <li><a href="#tab2">Tab 2</a></li>
        </ul>
    </div>		<!-- .block_head ends -->



    <div class="block_content tab_content" id="tab1">

        <h3>This is the first tab</h3>

        <p>Maecenas facilisis interdum rhoncus. Sed laoreet vulputate lacus sit amet aliquam. Praesent vitae sapien orci. Mauris nec purus in mi accumsan convallis non et lorem. Nunc tincidunt consequat risus, ac tincidunt nibh hendrerit at. Nullam sit amet nisi eget magna lacinia ullamcorper non sed sem. Ut ornare consequat commodo. Donec vitae justo risus. Nulla ornare posuere egestas. Nulla varius purus quis lacus placerat tincidunt.</p>

    </div>		<!-- .block_content ends -->



    <div class="block_content tab_content" id="tab2">

        <h3>This is the second tab</h3>

        <p>Praesent vitae sapien orci. Mauris nec purus in mi accumsan convallis non et lorem. Nunc tincidunt consequat risus, ac tincidunt nibh hendrerit at. Nullam sit amet nisi eget magna lacinia ullamcorper non sed sem. Ut ornare consequat commodo. Donec vitae justo risus. Nulla ornare posuere egestas. Nulla varius purus quis lacus placerat tincidunt. Maecenas facilisis interdum rhoncus. Sed laoreet vulputate lacus sit amet aliquam.</p>

    </div>		<!-- .block_content ends -->
</div>		<!-- .block ends -->