<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/css/form.css" type="text/css" media="screen"
      charset="utf-8"/>
<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/css/structure.css" type="text/css" media="screen"
      charset="utf-8"/>

<div id="frmContainer">
<h1 id="logo"><a href="#">www.ziown.com</a></h1>

<form method="post" action="<?php echo $this->baseUrl()?>form/send/name/<?php echo $this->form->getSlug()?>" enctype="multipart/form-data" name="form1" id="ziownForm" class="ziownUi leftLabel">

<div id="frmHeader" class="formInfo">
    <h2><?php echo $this->form->getName()?></h2>

    <p><?php echo $this->form->getDescription()?></p>
</div>

<ul>

<?php foreach ($this->form->getFields() as $field):?>
    <?php if($field->getType()->getType() == 'text'):?>
        <li>
            <label id="title<?php echo $field->getId()?>" for="Field<?php echo $field->getId()?>" class="fldTitle">
                <?php echo $field->getName();?>
                <?php if($field->getRequired()):?>
                    <span class="req">*</span>
                <?php endif;?>
            </label>

            <div>
                <input id="Field_<?php echo $field->getId()?>" name="Field_<?php echo $field->getId()?>"
                       type="text" tabindex="<?php echo $field->getPosition()?>"
                       value="<?php echo $field->getDefaultValue()?>"
                       size="<?php echo $field->getSize()?>"
                       class="large <?php echo $field->getRequired() ? 'validate[required]' : 'ziown-text'?>" />
            </div>
        </li>

    <?php elseif($field->getType()->getType() == 'number'):?>
        <li>
            <label id="title<?php echo $field->getId()?>" for="Field<?php echo $field->getId()?>" class="fldTitle">
                <?php echo $field->getName();?>
                <?php if($field->getRequired()):?>
                    <span class="req">*</span>
                <?php endif;?>
            </label>

            <div>
                <input id="Field_<?php echo $field->getId()?>" name="Field_<?php echo $field->getId()?>"
                       type="text" tabindex="<?php echo $field->getPosition()?>"
                       value="<?php echo $field->getDefaultValue()?>"
                       size="<?php echo $field->getSize()?>"
                       class="large <?php echo $field->getRequired() ? 'validate[required,custom[onlyNumber]]' : 'ziown-text'?>" />
            </div>
        </li>
    <?php elseif($field->getType()->getType() == 'textarea'):?>
        <li>
            <label id="title<?php echo $field->getId()?>" for="Field<?php echo $field->getId()?>" class="fldTitle">
                <?php echo $field->getName();?>
                <?php if($field->getRequired()):?>
                    <span class="req">*</span>
                <?php endif;?>
            </label>

            <div>
                <textarea id="Field<?php echo $field->getId()?>" name="Field<?php echo $field->getId()?>"
                          class="large <?php echo $field->getRequired() ? 'required' : ''?>" spellcheck="true" rows="<?php echo $field->getRows()?>"
                          cols="<?php echo $field->getCols()?>" tabindex="<?php echo $field->getPosition()?>"> </textarea>
            </div>
        </li>
    <?php elseif($field->getType()->getType() == 'checkbox'):?>
        <?php $checkboxes = json_decode($field->getOptions());?>
        <li>
            <fieldset>
                <legend class="choiceFld">

                <?php echo $field->getName();?>
                <?php if($field->getRequired()):?>
                    <abbr title="Required Field" class="require">*</abbr>
                <?php endif;?>
                </legend>
                <div class="blockStyle">
                    <?php foreach($checkboxes as $checkbox):?>
                        <?php $checked = $checkbox->is_default == 1 ? 'checked = "checked"' : '';?>
                                <span>
                                <input name="field<?php echo $field->getId()?>" class="checkbox" type="checkbox" value="<?php echo $checkbox->option?>" id="element_<?php echo $field->getId()?>"  <?php echo $checked ?>>
                                <label class="choice"><?php echo $checkbox->option;?></label>
                                </span>

                    <?php endforeach;?>
                </div>
            </fieldset>
        </li>
    <?php elseif($field->getType()->getType() == 'radio'):?>
        <?php $radios = json_decode($field->getOptions());?>
        <li>
            <fieldset>
                <legend class="choiceFld">

                <?php echo $field->getName();?>
                <?php if($field->getRequired()):?>
                    <abbr title="Required Field" class="require">*</abbr>
                <?php endif;?>
                </legend>
                <div class="blockStyle">
                    <?php foreach($radios as $radio):?>
                        <?php $selected = $radio->is_default == 1 ? 'checked = "checked"' : '';?>
                                <span>
                                <input name="field<?php echo $field->getId()?>" class="radio" type="radio" value="<?php echo $radio->option?>" id="element_<?php echo $field->getId()?>"  <?php echo $selected ?>>
                                <label class="choice"><?php echo $radio->option;?></label>
                                </span>

                        <?php endforeach;?>
                </div>
            </fieldset>
        </li>
    <?php elseif($field->getType()->getType() == 'section_break'):?>
        <li>
            <div>
                <h3><?php echo $field->getName()?></h3>
                <p><?php echo $field->getInstructions()?></p>
            </div>
        </li>
    <?php elseif($field->getType()->getType() == 'select'):?>
        <?php $selects = json_decode($field->getOptions());?>
        <li>
             <label id="title<?php echo $field->getId()?>" for="Field<?php echo $field->getId()?>" class="fldTitle">
                <?php echo $field->getName();?>
                <?php if($field->getRequired()):?>
                    <span class="req">*</span>
                <?php endif;?>
            </label>

            <div>
                <select name="element_<?php echo $field->getId()?>" id="element_<?php echo $field->getId()?>">
                        <?php foreach($selects as $select):?>
                        <?php $selected = $select->is_default == 1 ? 'selected = "selected"' : '';?>
                        <option value="<?php echo $select->option?>" <?php echo $selected ?>><?php echo $select->option?></option>
                        <?php endforeach;?>
                        </select>
            </div>
        </li>
    <?php elseif($field->getType()->getType() == 'name'):?>
        <li>
            <label id="title<?php echo $field->getId()?>" for="Field<?php echo $field->getId()?>" class="fldTitle">
                <?php echo $field->getName();?>
                <?php if($field->getRequired()):?>
                    <span class="req">*</span>
                <?php endif;?>
            </label>

            <div>
                        <span>
                        <input type="text" name ="element_<?php echo $field->getId()?>_firstname"
                               value="<?php echo $field->getDefaultValue()?>"
                               size="<?php echo $field->getSize()?>"
                               class="<?php echo $field->getRequired() ? 'validate[required]' : 'ziown-text'?>"
                               id="element_<?php echo $field->getId()?>_firstname" />

                        <label>First</label>
                        </span>
                        <span>
                        <input type="text" name ="element_<?php echo $field->getId()?>_lastname"
                               value="<?php echo $field->getDefaultValue()?>"
                               size="<?php echo $field->getSize()?>"
                               class="<?php echo $field->getRequired() ? 'validate[required]' : 'ziown-text'?>"
                               id="element_<?php echo $field->getId()?>_lastname" />
                        <label>Last</label>
                        </span>
            </div>
        </li>
    <?php elseif($field->getType()->getType() == 'street_address'):?>

    <?php elseif($field->getType()->getType() == 'file'):?>

    <?php elseif($field->getType()->getType() == 'datetime'):?>
        <li class="minLabel">
            <label id="title<?php echo $field->getId()?>" for="Field<?php echo $field->getId()?>" class="fldTitle">
                <?php echo $field->getName();?>
                <?php if($field->getRequired()):?>
                    <span class="req">*</span>
                <?php endif;?>
            </label>

            <div>
                        <span>
                        <input type="text" name ="element_<?php echo $field->getId()?>_mm"
                               value="<?php echo $field->getDefaultValue()?>"
                               size="<?php echo $field->getSize()?>"
                               class="<?php echo $field->getRequired() ? 'inputField inputAlign validate[required]' : 'inputField inputAlign'?>"
                               id="element_<?php echo $field->getId()?>_mm" />

                        <label>MM</label>
                        </span>
                        <span class="fldDivider">
                        -
                    <input name="" type="submit" value="submit">    </span>
                        <span>
                        <input type="text" name ="element_<?php echo $field->getId()?>_dd"
                               value="<?php echo $field->getDefaultValue()?>"
                               size="<?php echo $field->getSize()?>"
                               class="<?php echo $field->getRequired() ? 'inputField inputAlign validate[required]' : 'inputField inputAlign'?>"
                               id="element_<?php echo $field->getId()?>_dd" />

                        <label>DD</label></span>
                        <span class="fldDivider">
                        -
                        </span>
                        <span>
                        <input type="text" name ="element_<?php echo $field->getId()?>_yyyy"
                               value="<?php echo $field->getDefaultValue()?>"
                               size="<?php echo $field->getSize()?>"
                               class="<?php echo $field->getRequired() ? 'inputField inputAlign validate[required]' : 'inputField inputAlign'?>"
                               id="element_<?php echo $field->getId()?>_yyyy" />
                        <label>YYYY</label>
                        </span>
                        <span class="calander">
                        <a href="#" id="calander"><img src="images/date-pic.png" alt="Pick a date."/></a>
                        </span>
            </div>
        </li>
    <?php elseif($field->getType()->getType() == 'email'):?>
        <li>
            <label id="title<?php echo $field->getId()?>" for="Field<?php echo $field->getId()?>" class="fldTitle">
                <?php echo $field->getName();?>
                <?php if($field->getRequired()):?>
                    <span class="req">*</span>
                <?php endif;?>
            </label>

            <div>
                <input type="text" name ="element_<?php echo $field->getId()?>"
                       value="<?php echo $field->getDefaultValue()?>"
                       size="<?php echo $field->getSize()?>"
                       class="<?php echo $field->getRequired() ? 'large validate[required,custom[email]]' : 'large'?>"
                       id="element_<?php echo $field->getId()?>" />

            </div>
        </li>
    <?php elseif($field->getType()->getType() == 'phone'):?>
    <?php elseif($field->getType()->getType() == 'address'):?>
        <li>
            <label id="title<?php echo $field->getId()?>" for="Field<?php echo $field->getId()?>" class="fldTitle">
                <?php echo $field->getName();?>
                <?php if($field->getRequired()):?>
                    <span class="req">*</span>
                <?php endif;?>
            </label>

            <div>
                <input type="url" name ="element_<?php echo $field->getId()?>"
                       value="<?php echo $field->getDefaultValue()?>"
                       size="<?php echo $field->getSize()?>"
                       class="<?php echo $field->getRequired() ? 'required' : 'large'?>"
                       id="element_<?php echo $field->getId()?>" />

            </div>
        </li>
    <?php elseif($field->getType()->getType() == 'price'):?>
        <li>
            <label class="fldTitle">Price</label>

            <div>
                <span class="symbol">$</span>
                      <span>
                      <input name="field165" type="number" tabindex="31"/>
                      <label>Dollars</label>
                      </span>
                <span class="fldDivider">.</span>
                      <span class="cents">
                      <input name="field166" type="number" tabindex="32"/>
                      <label>Cents</label>
                      </span>
            </div>
        </li>
    <?php elseif($field->getType()->getType() == 'linkert'):?>

    <?php endif;?>
<?php endforeach;?>
<?php

    if ($this->form->getAntiSpam()) {
        $publicKey = '6LfLvrsSAAAAAHKPD-HAu3jolpxasdJnqbihRPBK ';
        echo recaptcha_get_html($publicKey);
    }

?>
<li class="buttons">
    <div>
        <input type="submit" value="<?php echo $this->form->getSendButtonName()?>"
               name="" align="<?php echo $this->form->getSendButtonAlign()?>" />
        
    </div>
</li>


</ul>
</form>
</div>

<script src="<?php echo $this->baseUrl()?>/assets/js/jquery-1.5.1.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/assets/js/jquery-ui-1.8.13.custom.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/assets/js/jquery.validationEngine-en.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/assets/js/jquery.validationEngine.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $("#ziownForm").validationEngine()
    });
</script>


