<select name="font_size" size="0" multiple>
    <option value="80%">8</option>
    <option value="85%">9</option>
    <option value="95%">10</option>
    <option value="100%">11</option>
    <option value="110%">12</option>
    <option value="140%">14</option>
    <option value="160%">16</option>
    <option value="180%">18</option>
    <option value="240%">24</option>
    <option value="280%">28</option>
    <option value="320%">32</option>
    <option value="360%">36</option>
    <option value="400%">40</option>
    <option value="450%">45</option>
    <option value="640%">64</option>
</select>