<div id="form-loader" class="formBody">
    <h1 id="frmHeader">
        <a style="background:url(assets/images/ziown-frm-logo.png) no-repeat left;" href="#">www.ziown.com</a>
    </h1>
    <form method="post" enctype="multipart/form-data" name="form1" id="form1" class="ziownUi leftLabel">
        <div class="formInfo">
            <h2 id="form-title">Form Title</h2>
            <p id="title-description">This is my form. Please fill it out. It's awesome!</p>
        </div>
        <ul id="form-body">
            <li>
                <label id="title1" for="Field1" class="fldTitle">Single Line Text</label>
                <div>
                    <input id="Field1" name="Field1" class="large form-field" type="text" maxlength="255" tabindex="1" value="Old Man and The Sea"/>
                </div>
            </li>
            <li>
                <label id="title2" for="Field2" class="fldTitle">Number</label>
                <div>
                    <input id="Field2" name="Field2" type="text" tabindex="2" class="large form-field" value="0123456789" />
                </div>
            </li>
            <li>
                <label id="title3" class="fldTitle">Paragraph Text</label>
                <div>
                    <textarea id="Field3" name="Field3" class="large form-field" spellcheck="true" rows="10" cols="50" tabindex="3">He was an old man who fished alone in a skiff in the Gulf 
Stream and he had gone eighty-four days now without taking a fish. In the first forty days a boy had been with him. 
                    </textarea>
                </div>
            </li>
            <li class="buttons">
                <div>
                    <input name="" type="submit" value="submit"/>
                </div>
            </li>
        </ul>
    </form>
</div>